All eslint rules only warn
nori-dot-eco/nori-dot-com pull request #240
Opened 2023-01-26 23:47 UTC by mrdave-dev

Developers are ignoring test suites because eslint is causing every build's overall status check to go red. We don't want to lose the information eslint is giving us, but we're not prepared to fix all eslint issues. 

This PR sets all rules to warn, such that we can have better signals for when tests break.

2023-01-26 23:47 UTC, scottynomad approved these changes

2023-01-27 00:02 UTC, jaycenhorton requested changes
@mrdave-dev I can't remember which thing breaks, but I'm fairly confident some rule or plugin definitely has an issue with root-level plugins.

Can we move this plugin into the overrides block like this:

```ts
{
      files: ['*'],
      plugins: ['only-warn'],
}
```

Looks good otherwise!

**Edit: it's [the graphql eslint plugin](https://github.com/B2o5T/graphql-eslint/blob/master/examples/multiple-projects-graphql-config/.eslintrc.cjs#L3)**

2023-01-27 05:38 UTC, jaycenhorton approved these changes

2023-01-27 05:38 UTC, jaycenhorton commented
Thanks!

2023-01-27 17:46 UTC, kyleclark171 approved these changes

2023-01-27 18:07 UTC, merged